### ISSUE TITLE
The wheat_TD.csv file downloaded from Github has the columns changed in order for the headers that start with 'category'

### ISSUE THREAD

**Issue by ShresthaR** [bioversity/Crop-Ontology#101]
https://github.com/Planteome/ibp-wheat-traits/tree/t3-wheat-traits
![CO_Wheat_Categories_Order_02](https://user-images.githubusercontent.com/11165978/94164268-6f834700-fe4e-11ea-9feb-667d6fcf6d3b.jpg)

**Comment by marieALaporte** [comment]
solved in new website, thanks to @TomHazekam
