### ISSUE TITLE
Label of an edited variable does not show up in header "Term information" and "Variables" window.

### ISSUE THREAD

**Issue by TomHazekam** [bioversity/Crop-Ontology#103]
I edited the variable name. The new name shows up in the 
Attributes but not on the label of the "Term information" (windows at right hand side). Also it shows a "<blank>"/empty variable name in the variable windows (bottom left) instead of the new variable name. Is this an indexing issue?!?
![image](https://user-images.githubusercontent.com/45200351/95463479-b1dd7580-0970-11eb-83e0-d669cfcf1f43.png)

**Comment by marieALaporte** [comment]
Closing as we released the new website
