### ISSUE TITLE
New site: meaning of the term relationship abbreviations?

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#111]
The terms must be linked with is_a, method_of, scale_of and possibly 'variable-of' like in the old site, unless there is another way that you decided to adopt?

**Comment by qlands** [comment]
Nodes in neo4j are linked with is_a, method_of, scale_of and possibly 'variable-of'. In some cases the relationship was not indicated then "related_to" was given.

The new browsing page shows now what each node type means: TE=Term, TR=Trait, ME=Method, SC=Scale, and VR=Variable.
