### ISSUE TITLE
New site: In search have % with 1 decimal

### ISSUE THREAD

**Issue by qlands** [bioversity/Crop-Ontology#118]

**Comment by elizabetharnaud** [comment]
Still:  When one search a term it is not showing the decimals when the % is under 1 
![Capture d’écran 2021-06-30 à 20 41 08](https://user-images.githubusercontent.com/1417541/124014263-95dca100-d9e3-11eb-86bb-4fe7af39f13c.png)

**Comment by qlands** [comment]
Thius has been fixed by Marie
