### ISSUE TITLE
New site: sync with the old site ?

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#119]
I corrected online in the current site the typos in the crop ontologies of Cassava and yam. When shall this be synchronize with the new site?

**Comment by marieALaporte** [comment]
when we will do the final synchronization before the launch

**Comment by elizabetharnaud** [comment]
OK. Just make sure  that all the banners I entered per crp will be preserved by the sync.

**Comment by elizabetharnaud** [comment]
done
