### ISSUE TITLE
Re-order the function

### ISSUE THREAD

**Issue by pypingou** [bioversity/Crop-Ontology#12]
At the moment all the functions defining the urls are in no particular order (all the / /api /about /video-tutorials ...)

Would you accept that we re-order them in alphabetical order ?

This way when you are at get-attributes you know where to look to find /terms or /rdf and so on.

**Comment by lmatteis** [comment]
Yes. Indeed I'm getting also a little worried about the size of `main.js`, which is quite huge. Maybe we can split it into different files/folders. But yes, ordering them alphabetically is a start! Once I get back from the conference I will also merge your other changes.
