### ISSUE TITLE
New site: We should add metadata to describe the ontologies 

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#120]
Metadata that are downloadable and are also accessible through the API to describe the ontology ( date, curator, modification...) - It could be entered when the ontology is uploaded, display in the ontology page and updatable by the curator

**Comment by qlands** [comment]
Hi @elizabetharnaud,

Is this the same as #123?

**Comment by elizabetharnaud** [comment]
@qlands : Yes the summary of the ontology creation & content should be in the metadata; good point

**Comment by elizabetharnaud** [comment]
Metadata in the RDF version- some metadata but not all.
At the level of the variable: institution and scientist as contributors, updating date, language
at ontology level: licence info
