### ISSUE TITLE
New site: Editing sections: alphabetical order

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#121]
would be good to have the list of sections in the site maintenance-section  page presented by alphabetical order.
![Capture d’écran 2021-03-22 à 19 44 41](https://user-images.githubusercontent.com/1417541/112041833-1ff4ae00-8b47-11eb-9c71-7f11a0675bfd.png)

**Comment by qlands** [comment]
Fixed in 1c5bda0e7376623213568fa650937d231a40642b
