### ISSUE TITLE
New site: Traits identified as terms and not traits

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#125]
some triats appear as 'Term' and should be 'Trait'
See example:
![Capture d’écran 2021-03-24 à 11 32 16](https://user-images.githubusercontent.com/1417541/112296767-6a844080-8c95-11eb-9487-00c1a0f47e71.png)

**Comment by qlands** [comment]
Same as #126 . We need to so some data cleaning

**Comment by qlands** [comment]
This was fixed in the last data cleaning
