### ISSUE TITLE
New site: Legend of graph visualization 

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#126]
The red colour is indicated for 'Term' but in the graph, it appears to be the colour of a 'Trait class'  (Agronomic traits) so could it be changed in the legend?

![Capture d’écran 2021-03-24 à 11 46 03](https://user-images.githubusercontent.com/1417541/112298058-e2069f80-8c96-11eb-9745-90b1a23bcb74.png)

**Comment by qlands** [comment]
That comes from the original data. The node "Agronomical traits" was not defined as a "Trait class" but without any definition therefore the current definition is "term". We need to do a bit of data cleaning.

**Comment by marieALaporte** [comment]
I can take a look at that, thanks @qlands

**Comment by qlands** [comment]
This was fixed by the last data cleaning
