### ISSUE TITLE
New site: photos in banners do not display

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#127]
One need to be logged in to see the photos in the banners
![Capture d’écran 2021-03-26 à 12 09 02](https://user-images.githubusercontent.com/1417541/112623662-e795ee00-8e2c-11eb-9f04-ae9ceec589cf.png)
 - it should be visible to anyone

**Comment by qlands** [comment]
Fixed by d8b0e1546bfacbc44d76663035c63030cff4e435
