### ISSUE TITLE
New Site: New created  page 'workflow'  does not appear in the upper menu beside 'about'

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#131]
![Capture d’écran 2021-06-17 à 08 10 38](https://user-images.githubusercontent.com/1417541/122341252-8d945880-cf43-11eb-99e5-076401a9fcad.png)

**Comment by qlands** [comment]
Fixed at a1d4aab91154c0ae2efe850edbf070934a6222d1
