### ISSUE TITLE
New Site: Text to change Homepage

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#132]
At the bottom of the homepage there is this sentence 'Crop Ontology by Integrated Breeding Platform is licensed under a Creative Commons Attribution 4.0 International License'
Please remove '_by Integrated Breeding Platform_'
Thanks

**Comment by qlands** [comment]
Fixed on ba5479d2c20bd4ef1729fcc80dc82be88d40750f
