### ISSUE TITLE
NEW SITE: Add the ontology name in the table of  suggested modifications

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#134]
When I logged as a curator to change a term in one ontology, the action is posted in the submission for review but the name fo th concerned ontology does not appear. It would be handy for approval to directly have the ontology name appearing.
![Capture d’écran 2021-06-23 à 13 33 32](https://user-images.githubusercontent.com/1417541/123090794-da3ad080-d428-11eb-84bd-6731908204c6.png)
![Capture d’écran 2021-06-23 à 13 33 54](https://user-images.githubusercontent.com/1417541/123090811-de66ee00-d428-11eb-9aa6-fce4684b4506.png)

**Comment by qlands** [comment]
This has been fixed in commit dc6211cb1abe7a0ff6ca1a21d5670e74852029a0
