### ISSUE TITLE
New site: variable box should only be displayed for Phenotype and Trait Ontology 

### ISSUE THREAD

**Issue by marieALaporte** [bioversity/Crop-Ontology#136]
The variable info box should only be displayed if the ontology is belonging to the 'Phenotype and Trait Ontology' set.

**Comment by qlands** [comment]
Hi @marieALaporte 

Is this still an issue? Or was it fixed by your latest code?

**Comment by marieALaporte** [comment]
no, it is not fixed. 
When someone goes to an ontologies that does not belong to the group 'Phenotype and Trait Ontology', there is no variable to be displayed so the section in the page should not be displayed. See screenshot attached
<img width="601" alt="Capture d’écran 2021-06-29 à 13 30 07" src="https://user-images.githubusercontent.com/5664149/123790167-4f514e80-d8de-11eb-81ed-3e0bea6c2370.png">

**Comment by qlands** [comment]
OK. Fixing it

**Comment by qlands** [comment]
Fixed in b2aabd904c3052b497ba234b391005f13a336eb6
