### ISSUE TITLE
NEW SITE make variable explicite

### ISSUE THREAD

**Issue by cpommier** [bioversity/Crop-Ontology#140]
From biologist feedback the triplet trait + method + scale should be explicitly displayed.
The current representation has methods below the trait. It should be variable below the trait, as in https://urgi.versailles.inra.fr/ontologyportal
The curent representation of variables was a workaround that is very confusing for biologists. This full update of the site is a good opportunity to update this.

**Comment by elizabetharnaud** [comment]
Ask for some clarification

**Comment by marieALaporte** [comment]
The trait, method and scale are now displayed on each variable detail page.
Is it addressing your comment @cpommier ?

**Comment by marieALaporte** [comment]
Closing for now as we added a link for each variable to the trait, method and scale that compose it.
Feel free to reopen @cpommier if that was not what you needed
