### ISSUE TITLE
NEW SITE Categories are not displayed in orden

### ISSUE THREAD

**Issue by vhualla** [bioversity/Crop-Ontology#141]
The categories are not displayed in the correct order, category_9 is below term_type, and then this ontology_name is in the middle of category 6 and 7

![image](https://user-images.githubusercontent.com/13644354/124030147-7fbaea80-d9bb-11eb-9994-4d6a7a1c7c8e.png)

**Comment by elizabetharnaud** [comment]
@qlands can sort the keys and @TomHazekam to check the original files

**Comment by marieALaporte** [comment]
fixed, the attributes are displayed in the correct order. It will be available with the next release
