### ISSUE TITLE
NEW SITE The potato_TD.csv file downloaded has the columns changed in order for the categories

### ISSUE THREAD

**Issue by vhualla** [bioversity/Crop-Ontology#142]
![image](https://user-images.githubusercontent.com/13644354/124032111-c7db0c80-d9bd-11eb-9d7c-84f43fac0e57.png)

**Comment by elizabetharnaud** [comment]
similar #141

**Comment by marieALaporte** [comment]
This is fixed for Potato. Thanks @vhualla for reporting this bug
