### ISSUE TITLE
New site Menu Tools: Add new terms  

### ISSUE THREAD

**Issue by vhualla** [bioversity/Crop-Ontology#143]
In the main menu add new terms does not go to any other link

![image](https://user-images.githubusercontent.com/13644354/124036143-2b1b6d80-d9c3-11eb-947b-adbbd8240793.png)

**Comment by elizabetharnaud** [comment]
@qlands add the feature

**Comment by qlands** [comment]
This is done. On the main page, next to each Trait ontologies there is a button to upload new terms.
