### ISSUE TITLE
NEW SITE: Do we want to keep the registration request feature?

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#146]
We had a registration request system to approve of reject registration request with allocation of rights to the user. Shall we keep that ?

**Comment by elizabetharnaud** [comment]
@elizabetharnaud Add New page describing how to add an ontology that indicates to contact the helpdesk to get an account.

**Comment by marieALaporte** [comment]
This is done. Closing now as you opened #172
