### ISSUE TITLE
NEW SITE: Management of Expert Group members

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#148]
When an ontology has an Expert group, the role is to validate modifications submitted. We need to see ho to declare the group members and create a kind of voting feature - like or dislike

**Comment by elizabetharnaud** [comment]
@elizabetharnaud and @marieALaporte to discuss

**Comment by marieALaporte** [comment]
Does the community website allow that?

**Comment by marieALaporte** [comment]
Closing for now, as having the validation by one person is enough. We would need someone to maintain the expert groups for this to work
