### ISSUE TITLE
NEW SITE : Display of scales

### ISSUE THREAD

**Issue by TomHazekam** [bioversity/Crop-Ontology#150]
Display of scale is missing while scale exists in downloaded file (see image marked in red)
![InkedCO_rev 1_LI](https://user-images.githubusercontent.com/45200351/124137063-3b901e80-da7d-11eb-9b0d-057c051cf598.jpg)

**Comment by dwaring87** [comment]
Many of the scales are also not displayed on the wheat ontology

**Comment by elizabetharnaud** [comment]
No immediate solution to solve this - to be discussed by  @qlands & @marieALaporte

**Comment by qlands** [comment]
@dwaring87  can you give us a screenshot of the missing scales?

**Comment by dwaring87** [comment]
Here are a couple of examples:

- The Awn Color trait shows the proper method and scale in the tree
- The Awn Length and Coleoptile Length traits show their methods, but not their scales (in both of these cases the "cm" scale should be shown.

![image](https://user-images.githubusercontent.com/7526014/131144286-c86daff4-5656-419e-b5d6-f5104cdb55db.png)

Clicking on the variable button does list the cm scale

![image](https://user-images.githubusercontent.com/7526014/131144999-739f1e42-8227-48a0-af42-49ecd3a1df6f.png)

**Comment by marieALaporte** [comment]
should be fixed once we update the ontologies to be compliant to TD v5.1
