### ISSUE TITLE
NEW SITE: Feedback loop requested term revisions

### ISSUE THREAD

**Issue by TomHazekam** [bioversity/Crop-Ontology#151]
Not sure whether this is implemented, but it would be nice to have a good feedback loop on any requested term modifications e.g. :
- submitter receives automatic confirmation of pending request and who is managing the request;
- ontology manager is automatically notified of any requests submitted;
- submitter is automatically notified when the status of their request changes

**Comment by imsachaves** [comment]
As one of the Woody Plant Ontology curator, I can't see the items to be approved
<img width="1168" alt="Captura de ecrã 2022-10-09, às 18 48 39" src="https://user-images.githubusercontent.com/16034650/194771847-13331e19-bf16-4676-b69f-6627414a11ce.png">

**Comment by elizabetharnaud** [comment]
TEST SITE: I logged in with my usual login and made a change in the sweet potato ontology, in the definition of [CO_331:0002069](https://co.formshare.org/rdf/CO_331:0002069) but when I went in the ‘revision’ menu:
I click on ‘Review changes ‘ and got a 404 error
no issue was created in Github.
when I checked on ‘Accept’, the revision was accepted and appears in the record
