### ISSUE TITLE
New Site: a section for Food products

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#155]
We are developing TD for the traits of Food Products, mainly roots, tubers and bananas. would be great to have a section on this. To be discussed

**Comment by marieALaporte** [comment]
@elizabetharnaud Do we still want that? Some variables have been added to the existing ontologies directly. 
If not needed anymore, we can close the issue

**Comment by elizabetharnaud** [comment]
Que fais-ton avec cette suggestion? nous avons discuté de mettre une sous classe texture avec Naama et Amos.

**Comment by marieALaporte** [comment]
Closing, as we won't be implementing this through a new section, but through a new subclass of Quality Traits
