### ISSUE TITLE
New Site: Font Awesome Icons Missing

### ISSUE THREAD

**Issue by dwaring87** [bioversity/Crop-Ontology#156]
The font awesome icons are not displayed (MS Edge, Mac) on the search page

![Screen Shot 2021-07-09 at 10 36 07 AM](https://user-images.githubusercontent.com/7526014/125095537-47de3200-e0a2-11eb-9bb2-883ea3cb349b.png)

**Comment by elizabetharnaud** [comment]
Hi Carlos, would be great to have this icone display problem fixed.

**Comment by marieALaporte** [comment]
will be fixed in new release
