### ISSUE TITLE
New Site: Clearer display of variable composition

### ISSUE THREAD

**Issue by dwaring87** [bioversity/Crop-Ontology#157]
The ontology browser does a great job of displaying the hierarchy of traits, methods and scales.  However, it is not clear which traits, methods and scales compose a variable.

To get to this display, I clicked the trait and then the button for one of the variables.  The right panel displays the attributes of the variable.  But, how do I know which trait, method and scale are used for this variable?  I think having that clearly displayed in the list of variable attributes and highlighted in the ontology tree would be very useful.

![Screen Shot 2021-07-09 at 10 49 09 AM](https://user-images.githubusercontent.com/7526014/125097251-efa82f80-e0a3-11eb-8f3f-3e702ae15703.png)

**Comment by qlands** [comment]
This has been fixed in acbdffea065ec6f10acc5cb755baddb535aeb9b6
