### ISSUE TITLE
Update of the Bambara TD with X references

### ISSUE THREAD

**Issue by LilyAndres** [bioversity/Crop-Ontology#158]
Hello CO team, I am creating this issue because I have been mapping some of the `trait names` from bambara groundnut to the PO and TO, which I think are the OBO ontologies that CO intends to use as X ref. There are some terms that do not have an exact match with some of these OBO ontologies, for this reason, I tried to map as much as possible using the EQ model, please see my example below: 

- for the term `'Terminal leaflet colour'` in the column "Trait Xref" I have `'leaflet' [PO:0020049]`, `'color' [PATO:0000014]`.

- For the term `'Alternaria leaf spot susceptibility'` I have `'whole plant' [PO:0000003]` (because I couldn't find a better term from PO or TO)

- For the term `'Maturity time'` I have  `'whole plant' [PO:0000003]` and `'maturity' [PATO:0000261]`

These are examples, but may be worth highlighting it and describe the correct process in the guidelines? Because this is the link point with OBO ontologies (PO and TO) and I want to make sure that what I am doing is correct. There are some other terms that can be reused, but they are not from PO or TO, instead they are from NCIT, ENVO and CDNO.

Happy to discuss it, I can also send the draft I have as well.

Thanks.

**Comment by marieALaporte** [comment]
Should be available online now. 
Feel free to reopen if you think we should display the information differently
