### ISSUE TITLE
Update defintion for grain yield

### ISSUE THREAD

**Issue by celineaubert** [bioversity/Crop-Ontology#162]
Salut Marie,

Some definitions of grain yield are missing the idea of unit area. Could you update them?

- wheat : http://www.cropontology.org/rdf/CO_321:0000013
- -cowpea: http://www.cropontology.org/rdf/CO_340:0000638
- common bean: http://www.cropontology.org/rdf/CO_335:0000068 - is it grain yield? if yes, need to add it to the name

**Comment by marieALaporte** [comment]
Could you please open a ticket on the crop repo for wheat and cowpea?
https://github.com/Planteome/CO_321-wheat-traits/issues
https://github.com/Planteome/CO_340-cowpea-traits/issues

For common bean, we are in the process of working on the new version of the ontology. I will let the curator know your comment @TomHazekam 

Closing the issue as it is not about the website.
