### ISSUE TITLE
appcfg.sh, application id confusion

### ISSUE THREAD

**Issue by Dave-Matthews** [bioversity/Crop-Ontology#17]
When I follow README.md and run "appcfg.sh" it seems to want my Google id and password.  When I did that it said:

Unable to update app: Error posting to URL: https://appengine.google.com/api/appversion/create?app_id=cropontology-curationtool&version=2&
404 Not Found
This application does not exist (app_id=u'cropontology-curationtool').

Do I need to create it myself?  Didn't you already do it?
- Dave

**Comment by lmatteis** [comment]
Hi Dave! Yes you need to create an AppEngine app. Such as <app_id>.appspot.com.
Go to http://appengine.google.com/ and create your app, then change `appengine-web.xml` with the new id and try deploying it. You'll have to enter the credentials of the Google account where you created the App Engine app. Let me know if this works!

**Comment by Dave-Matthews** [comment]
Yes it works.  http://t3ontology.appspot.com
This is my first exposure to appengine and I wasn't even grasping the
concept.  Thanks!
- Dave
  (more questions for you on the cropontology.org Disqus board)

**Comment by lmatteis** [comment]
I see you're getting an error with the `/get-ontologies` endpoint. Let me know what your logs are saying so maybe I can fix this.

**Comment by Dave-Matthews** [comment]
Nothing relevant in the apache error.log or /var/log/syslog on my Ubuntu server where my t3ontology is "running".  Are you asking about my problem doing a DOWNLOAD of an ontology from cropontology.org in Trait Template format?

**Comment by lmatteis** [comment]
apache? Aren't you using App Engine?

**Comment by Dave-Matthews** [comment]
> > > Let me know what your logs are saying so maybe I can fix this.
> > 
> > Nothing relevant in the apache error.log or /var/log/syslog
> 
> apache? Aren't you using App Engine?

Yes I am.  I didn't/don't understand your comment that I'm getting an error with the /get-ontologies endpoint, so I don't know what logs you want me to tell you about.  Did I say something about get-ontologies?  Is this error in something I'm doing in my t3ontology.appspot.com copy or on your cropontology.org copy?

**Comment by gubi** [comment]
For future purposes, this is a simple step guide.

Open a Google Cloud Shell and type following commands:
1. Download the [App Engine Java SDK](https://cloud.google.com/appengine/docs/standard/java/download) with this command (for eg. version 1.9.64):<br>`wget https://storage.googleapis.com/appengine-sdks/featured/appengine-java-sdk-1.9.64.zip`
2. Clone this repo in the same directory of the `appengine-sdk`:<br>`git clone https://github.com/bioversity/Crop-Ontology.git`
3. Deploy all with this command:<br>`sh appengine-sdk/bin/appcfg.sh update Crop-Ontology`

**Comment by marieALaporte** [comment]
The steps to run the server locally are:

1. Download the App Engine Java SDK with this command (for eg. version 1.9.64):
`wget https://storage.googleapis.com/appengine-sdks/featured/appengine-java-sdk-1.9.64.zip`
2. Clone this repo in the same directory of the appengine-sdk:
`git clone https://github.com/bioversity/Crop-Ontology.git`
3. Deploy all with this command:
`sh appengine-sdk/bin/dev_appserver.sh --port=3000 Crop-Ontology`

**Comment by gubi** [comment]
I'm working on App Engine compatibility fixes in [this repository](https://github.com/gubi/Google-App-Engine-1.9.64-FIXES)
