### ISSUE TITLE
Disqus comments disappearing

### ISSUE THREAD

**Issue by Dave-Matthews** [bioversity/Crop-Ontology#18]
At http://www.cropontology.org/feedback the comment I've added three times in the last few hours keeps disappearing.  The ones I added 13+ hours ago are still there.  
(It said "I'm getting a mainly empty file when I try the "Trait Template v4" DOWNLOAD of Wheat Trait, http://www.cropontology.org/ontology/CO_321/Wheat%20trait
The OBO file is fine.")

**Comment by lmatteis** [comment]
Weird, maybe it's some issue with Disqus (the comment system we're using). Anyhow, I replied to your questions. Maybe we can keep discussions on github since it seems more reliable. 

Yes, the empty file is kind of a "Getting Started" table that you can use to build your ontology from scratch. You probably don't need this if you already have an Ontology.

**Comment by lmatteis** [comment]
Wait, is it because you used the other comment page on http://www.cropontology.org/api ?

**Comment by Dave-Matthews** [comment]
> Wait, is it because you used the other comment page on http://www.cropontology.org/api ?

Actually I did also lose the first try at a comment on the API page, but the second one stuck.  The ones that repeatedly disappeared were at http://www.cropontology.org/feedback.

**Comment by Dave-Matthews** [comment]
> > "I'm getting a mainly empty file when I try the "Trait Template v4" DOWNLOAD of Wheat Trait, 
> > http://www.cropontology.org/ontology/CO_321/Wheat%20trait
> > The OBO file is fine."
> 
> Yes, the empty file is kind of a "Getting Started" table that you can use to build your ontology from scratch. 
> You probably don't need this if you already have an Ontology.

Are you sure you want this result of clicking the red "DOWNLOAD" button in the upper left of the ontology-tree pane to be only a Getting Started table?  As I said, the OBO file is fully populated.  Also the "Trait Template v4" for Sorghum is fully populated.  Seems like this is what people expect from a Download.  As a template for getting started, the file TraitTemplate_ver_4.xls that you get from going to 
http://www.cropontology.org/add-ontology#!/add/upload_excel and clicking "Upload Excel Trait Template" is much more useful.  

(No I don't already have one.)

**Comment by marieALaporte** [comment]
Fixed
