### ISSUE TITLE
Change 'Term' Category for Classes

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#181]
The classes are identified as 'Term' in the site. Could it be changde for 'Class'?

**Comment by marieALaporte** [comment]
We agreed before releasing the site to keep the grouping terms as 'Class' and the subclasses as 'Traits'. All the ontologies were curated like that. Changing that will require a re-indexing of everything. Do you want to do that or can we keep it as it is?

**Comment by marieALaporte** [comment]
@elizabetharnaud Can we keep Term for the grouping categories? Everything is a Class (trait, method, scale, variable), so better to have a generic term for the grouping caterogies. 
If you agree with keeping Term, close the issue
