### ISSUE TITLE
Graph visualization: inconsistency with the Tree vizualization

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#185]
for the woody species, the graph show 2 variables DGA, DGB for the 'Branh Diameter' and one Method 'Callipe Protocol'  - Variables are directly linked to the Trait on the graph. see image #1
![Capture d’écran 2022-05-18 à 11 42 52](https://user-images.githubusercontent.com/1417541/169011746-3086e03a-573c-437d-97c6-991c9e3e5769.png)

In the Tree Structure,  DGB - DGA appear when you select the trait while only DGB appear when you click on the Method so DGB seems linked to the Callipe Method here. figure#2 & #3
![Capture d’écran 2022-05-18 à 11 56 40](https://user-images.githubusercontent.com/1417541/169012981-5ae1704b-f428-480f-9e48-75e475ddbb3b.png)
![Capture d’écran 2022-05-18 à 11 56 47](https://user-images.githubusercontent.com/1417541/169013010-117e21d6-d8ce-4950-94aa-ac9f5d70aeec.png)

Why do we have such a descripency?

**Comment by marieALaporte** [comment]
I think that's content issue. I will look at the data here

**Comment by elizabetharnaud** [comment]
Dupicate of #186
