### ISSUE TITLE
CO_357 can't parse in AgroPortal

### ISSUE THREAD

**Issue by jonquet** [bioversity/Crop-Ontology#195]
This is a handler for https://github.com/agroportal/project-management/issues/202
It seems the work is done on @cmichotey 's side and it needs refactoring/validation by Crop Ontology

**Comment by jonquet** [comment]
I am not sure why this issue was closed without any news on the AgroPortal related issue. 
On our side CO_357 still can't parse: 

<img width="1634" alt="image" src="https://user-images.githubusercontent.com/7379183/210255461-a77f97bf-3264-4801-8b80-e69e4c00cecf.png">

**Comment by elizabetharnaud** [comment]
Hi not sure why it was closed... perhaps an error or because there is already a similar issue ?
