### ISSUE TITLE
URGENT - Upload of New ontology Fails-Sainfoin

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#198]
i created a page but made first a mistake in the code  C0_369 instead of CO_369. However the Sainfoin ontology was listed in the home page. I deleted the ontology from the homepage using the delete icone. I recretaed a apge with the proper code but the system indicated that the page already exists! Wehn I try to upload the TD, I get an error that the page does not exists...
<img width="987" alt="Capture d’écran 2022-11-10 à 07 01 14" src="https://user-images.githubusercontent.com/1417541/201015355-89503f49-fb1e-44ed-a545-b35957c598c1.png">
<img width="813" alt="Capture d’écran 2022-11-10 à 07 03 12" src="https://user-images.githubusercontent.com/1417541/201015365-09d42c91-891f-4fdd-9d39-f879db1ed2e7.png">

**Comment by marieALaporte** [comment]
fixed. The ontology is now online
