### ISSUE TITLE
404 Error for CO_369 Sainfoin Trait Dictionary

### ISSUE THREAD

**Issue by BoMeyering** [bioversity/Crop-Ontology#201]
I need to make some additions to the trait dictionary for Sainfoin CO_369. But when you try to download the TD, it returns a 404 error. This also happens when I try to upload the original trait dictionary that I added a few terms to. If loads for a while and then returns the screen below. Any help fixing these links is much appreciated!

![image](https://user-images.githubusercontent.com/106114773/223854736-70ea2ef7-bb79-4a29-9850-ff6771547377.png)

**Comment by marieALaporte** [comment]
Issue was resolved.
