### ISSUE TITLE
Update ontology on GitHub

### ISSUE THREAD

**Issue by marieALaporte** [bioversity/Crop-Ontology#202]
When an ontology is uploaded on the website, update the corresponding csv file on [Planteome GitHub](https://github.com/Planteome)

**Comment by elizabetharnaud** [comment]
TEST SITE: BUG
When a term is modified in the site, it does not create an issue in Planteome Github

**Comment by elizabetharnaud** [comment]
i still can't see any impact of my modifications in Github. Is tbhis activated for my login?

**Comment by elizabetharnaud** [comment]
Does not work for now because probably the token is not copied on the production site.

**Comment by elizabetharnaud** [comment]
@acoto @marieALaporte @qlands : Shall we close this iussue now?
