### ISSUE TITLE
Yam: 404-Page not found for a variable

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#207]
When searching germination rate for Yam, the resulting lits shows the following:

![Capture d’écran 2023-07-26 à 09 53 22](https://github.com/bioversity/Crop-Ontology/assets/1417541/99699273-d23a-4395-9498-90a9909b4ca6)
 and when clicking on the term: 
[CO_343:0000294](https://cropontology.org/term/CO_343:0000294) Variable Seed germination rate percentage

we get an error 404 page not found.

**Comment by marieALaporte** [comment]
will be live when we update the server
