### ISSUE TITLE
Common Bean: trait found by search but not displayed 

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#208]
Regarding 'Maturity time' with a filter on common bean: the result list returns:
![Capture d’écran 2023-07-26 à 10 40 22](https://github.com/bioversity/Crop-Ontology/assets/1417541/2c263169-9708-4f64-bab2-88ac7cec175c)

However, the site does not display some traits in the tree in the left  window while it displays the metadata in the right window 
these traits are :
[CO_335:0000016](https://cropontology.org/rdf/CO_335:0000016) rait Plant days to physiological maturity
[CO_335:0000154](https://cropontology.org/term/CO_335:0000154) Trait Physiological maturity date
[CO_335:0000872](https://cropontology.org/term/CO_335:0000872) Trait Physiological maturity date
[CO_335:0000875](https://cropontology.org/term/CO_335:0000875) Trait Plant days to physiological maturity

![Capture d’écran 2023-07-26 à 10 42 02](https://github.com/bioversity/Crop-Ontology/assets/1417541/9bb183c8-c58b-4415-9d7d-9958638e80cf)

**Comment by marieALaporte** [comment]
The index used for the search was not refreshed so was calling a old version of the ontology. Fixed now. But will open an issue for updating the index every time a TD is loaded
