### ISSUE TITLE
Entity & Attribute: use as filters

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#218]
We have 2 columns in the TD: Entity (Plant part obersved) and Attribute ( attribute to measure/observe). We always suggested to use the Entity to have a way of filtering traits per plant part (e.g. root, leave, full plant) - Would it be possible to add this feature?

**Comment by marieALaporte** [comment]
this can be done by using the filter on the Entity field. Once you select the entity filter, you can pick the entity you want to use for the search
