### ISSUE TITLE
Error 404: page missing to set managers for an ontology

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#223]
in menu, 'Sections','Set managers'

**Comment by qlands** [comment]
It seems that the code must be adapted to run on Python 3.8.10. I think it the best so move the CropOntology Code into docker containers just like ClimMob and FormShare.

I will work on moving the code into a Docker this week.

**Comment by elizabetharnaud** [comment]
@carlos : Could you set a deadline for resolving this issue?

**Comment by qlands** [comment]
Hi @elizabetharnaud I been working on the containers and a series of scripts to enable the process of having the CO website in docker. I am confident that by mid next week the site will run over Docker

**Comment by elizabetharnaud** [comment]
@qlands Thanks! We will receive a new Finger Millet ontology.  I encourage the curators to manage their banner. and this bg blocks this option.

**Comment by qlands** [comment]
Hi @elizabetharnaud. I made an update on the server. Can you check if this error still happens?

**Comment by elizabetharnaud** [comment]
@qlands It works now! thanks a lot . we can close the issue.
