### ISSUE TITLE
CO site Github Site alert: Master branch 2.0 is not protected

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#225]
What does it mean and how to act on this?
![Capture d’écran 2024-01-31 à 10 10 17](https://github.com/bioversity/Crop-Ontology/assets/1417541/2da8ebd2-2697-467e-8eb6-6f4bfebad481)

**Comment by marieALaporte** [comment]
Only admins of the repo see this message.
Protected branches are a feature in GitHub repositories used to prevent unauthorized or accidental changes. It is a good practice to have that as it ensures that changes to the branch meet specific quality. It is mainly used by collaborative projects, where a lot of people contribute code. In our case, this is not really necessary to have our main branch protected. 
Closing the issue for now then
