### ISSUE TITLE
RDF service bugs/improvements

### ISSUE THREAD

**Issue by ansell** [bioversity/Crop-Ontology#25]
I downloaded the full document from the following to experiment:

```
http://www.cropontology.org/ontology/CO_343/Yam/ttl
```

There are some URIs, in my investigations using CO_343, that work, while others fail. It contains links to various URIs using the following format, for example: However, the following fails with an HTTP 500 error.

```
http://www.cropontology.org/rdf/CO_343:ROOT
```

The following, and most other subset URIs, however work:

```
http://www.cropontology.org/rdf/CO_343:Physiological
```

I have a few queries in addition to fixing those HTTP 500 errors:
1. Would it be possible to have a content negotiated way of getting the entire ontology if you only know its CO_NNN number? The current method only works if you know the alias, and you know which formats are currently supported for the ontology.

It would be ideal if I could send the following HTTP Accept header (or similar) to a URI that is defined just using CO_NNN and either redirect to another URI or directly return an RDF document in one of those syntaxes (or fail with HTTP 406 if that isn't possible):

```
Accept: text/turtle, application/rdf+xml, application/rdf+json
```
1. Would it be possible to add the rdfs:isDefinedBy links to the subsets and make them link back to the entire ontology URI that is content negotiated? 

Ie, 

```
<http://www.cropontology.org/rdf/CO_343:Physiological> rdfs:isDefinedBy <http://www.cropontology.org/rdf/CO_343>
```

(or something similar based on changes in 1)
1. Would it be possible to add all of the languages labels to the subsets? 

It is fairly easy to select based on language tags, but it appears as though either English is being selected for me based on my location or HTTP Request headers, or it is the only available label in those cases and you need to download the entire ontology to get the other labels.

**Comment by lmatteis** [comment]
Hi Peter,

Yes there are some issues with the HTTP server, returning errors when it shouldn't. We are working to fix those asap.

> Would it be possible to have a content negotiated way of getting the entire ontology if you only know its CO_NNN number? The current method only works if you know the alias, and you know which formats are currently supported for the ontology.

This is a very specific request... is there a standard way of doing this in Linked Data? Afaik in order to be proper LD you simply need to provide resolvable URIs which resolve to one of the popular RDF formats (we only support RDF/XML for single URIs and Turtle for the entire ontology but may add further formats). But I'm not sure I understand entirely your request; can you give me an example?

> Would it be possible to add the rdfs:isDefinedBy links to the subsets and make them link back to the entire ontology URI that is content negotiated?

Yes absolutely, sounds like the right way of doing it. May I ask how you're using this relationship?

> Would it be possible to add all of the languages labels to the subsets?

The Turtle dump contains all the languages. Only the single URIs resolver doesn't (which only returns RDF/XML). You're right we should add the language labels to the single URIs resolver, and I'll be doing this asap.

**Comment by ansell** [comment]
On 15 July 2013 22:06, Luca Matteis wrote:

> Hi Peter,
> 
> Yes there are some issues with the HTTP server, returning errors when it
> shouldn't. We are working to fix those asap.
> 
> Would it be possible to have a content negotiated way of getting the
> entire ontology if you only know its CO_NNN number? The current method only
> works if you know the alias, and you know which formats are currently
> supported for the ontology.
> 
> This is a very specific request... is there a standard way of doing this
> in Linked Data? Afaik in order to be proper LD you simply need to provide
> resolvable URIs which resolve to one of the popular RDF formats (we only
> support RDF/XML for single URIs and Turtle for the entire ontology but may
> add further formats). But I'm not sure I understand entirely your request;
> can you give me an example?

In Linked Data, the authoritative URI for an item, in this case an
ontology, can be resolved to either HTML, RDF, or other formats, based on
the clients HTTP Accept header. If a browser requests the page they will
not likely put "application/rdf+xml" or "text/turtle".  It doesn't really
matter which RDF formats you currently support for each feature, as most
toolkits support more than one format, but it is useful to respond
differently to the same URL if you detect that they user is requesting the
supported format. You can safely send a user agent "text/html" as a backup,
even if they didn't request it specifically but they had a "_/_" in the
list.

The main key is to establish an authoritative URI for the ontology, (and
authoritative URIs for the single URIs), and refer to them in RDF documents
using the same URI as in HTML documents.

The current URIs look like:

Request HTML:

```
http://www.cropontology.org/ontology/CO_343/Yam
```

Request Turtle:

```
http://www.cropontology.org/ontology/CO_343/Yam/ttl
```

Request a term from ontology:

```
http://www.cropontology.org/rdf/CO_343:Physiological
```

RDFS:isDefinedBy from term to HTML page about that term

```
http://www.cropontology.org/terms/CO_343:Physiological
```

It may be cleaner to change to something like the following strategy

Content negotiated request for full ontology, redirected using HTTP 303 or
HTTP 302 to a format specific URL:

```
http://www.cropontology.org/ontology/CO_343
```

Request HTML:

```
http://www.cropontology.org/html/ontology/CO_343
```

Request Turtle:

```
http://www.cropontology.org/ttl/ontology/CO_343l
```

Content negotiated request for a term from ontology, redirecting with
either HTTP 303 or HTTP 302 to HTML by default if there is no other
preference given:

```
http://www.cropontology.org/term/CO_343:Physiological
```

Specifically request HTML:

```
http://www.cropontology.org/html/term/CO_343:Physiological
```

Specifically request RDF/XML:

```
http://www.cropontology.org/rdfxml/term/CO_343:Physiological
```

It looks substantially different to what you have now, as it only uses
prefixes for the format specific URLs. My experience has been designing the
Bio2RDF URI scheme, so I prefer prefixes, but it is also perfectly
acceptable to standardise on suffixes for the format specific URLs.

For example, the following may correspond to what is above if they were
ever added to Bio2RDF, although these URLs are hypothetical:

```
http://bio2rdf.org/co_343:Physiological

http://bio2rdf.org/page/co_343:Physiological   (/html/ was reserved
```

early on for finding outbound html links, so /page/ is used for the HTML
representation)

```
http://bio2rdf.org/rdfxml/co_343:Physiological

http://bio2rdf.org/turtle/co_343:Physiological
```

My usecase for that URI format (or similar, where the key is just the
numeric identifier,) is initially to make it easy to determine whether
there is an RDF version currently available. Previously I have used the
OWLAPI OBO importer, with an OWLAPI RDF exporter to generate an RDF
versions of Crop Ontology 715, and it would be nice to know which
ontologies I still need to do that with using that method. However, in the
long term, it would be easier to have single methods for getting either the
whole ontology or specific URIs.

Another feature that can help some user agents who support both RDF and
HTML can be to put the following in the HTML page as a hint, where the href
is a URL that goes directly to the Turtle representation, and is not
content negotiated:

```
<link rel="alternate" type="text/turtle" href="...">
<link rel="alternate" type="application/rdf+xml" href="...">
```

 Would it be possible to add the rdfs:isDefinedBy links to the subsets and

> make them link back to the entire ontology URI that is content negotiated?
> 
> Yes absolutely, sounds like the right way of doing it. May I ask how
> you're using this relationship?
> 
> It is one pattern for getting full ontologies or documents if you only have
> a subset currently. I would be using it to direct people back to the full
> ontology from a subset if I was referencing the subset as a linked data
> URI, and it would be easier to copy the existing RDF triples than to
> recreate them.

The existing rdfs:isDefinedBy seems to be trying to redirect back to an
HTML page, although some of them have 404 or 500 errors right now. It is
more common to use foaf:page to link from the URI to an HTML page.

```
http://xmlns.com/foaf/spec/#term_page
```

>  Would it be possible to add all of the languages labels to the subsets?
> 
> The Turtle dump contains all the languages. Only the single URIs resolver
> doesn't (which only returns RDF/XML). You're right we should add the
> language labels to the single URIs resolver, and I'll be doing this asap.
> 
> Thanks

**Comment by lmatteis** [comment]
Hi Peter. We'll definitely take a closer look at all of your comments and we'll see to further implement them. 

For URIs I think you're right, however I'd simply rather have a single URI such as `/resource/CO_343:Physiological` which returns all the formats that you want based on HTTP Header content negotiation `Accept:text/turtle`

**Comment by ansell** [comment]
Sounds good.
