### ISSUE TITLE
Triples in the RDF output partly converted to html characters

### ISSUE THREAD

**Issue by pypingou** [bioversity/Crop-Ontology#29]
See http://www.cropontology.org/ontology/CO_020/FAO-IPGRI%20Multi-Crop%20Passport%20Descriptor/nt

The first line looks like:

```
<http://www.cropontology.org/rdf/CO_020%3A90> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/2004/02/skos/core#Concept> .
```

As you can see, the subject contains `%3A` where it should have `:`

By the way, maybe it should use the MIME type `text/turtle` instead of `text/plain`

**Comment by lmatteis** [comment]
Hello. Actually `%3A` is the correct URL encoding for `:`

**Comment by pypingou** [comment]
That might be but this is not html it's text and thus should not contain html characters

**Comment by lmatteis** [comment]
I'm not sure what you mean. Try this in JavaScript `encodeURIComponent(':')`.
The components between the slashes in a URI need to be encoded. And that's the appropriate encoding.

**Comment by pypingou** [comment]
> The components between the slashes in a URI need to be encoded

Where did you see this?

While trying to parse some of our generated rdf with rdflib (python) I ended up with two different URI, one with the html encoding the other without, so either we have a bug or they do :)

**Comment by lmatteis** [comment]
Go here: http://www.w3schools.com/tags/ref_urlencode.asp
In the little box enter something like `CO:12345`
Click submit.
HTML has nothing to do with anything. HTML is representation.

**Comment by pypingou** [comment]
If I understand the document correctly, these are URL not URI

**Comment by lmatteis** [comment]
Well I have a `CO:1234` that I need to put in the URL, so I simply run `encodeURIComponent()` on it. How else would I do it? If the CO identifier contains something like a slash `/` it would break the url. If there's another way of encoding it, I would happily make the change.

**Comment by pypingou** [comment]
I understand the needs to provide decent links on the UI but for the RDF output we used not to do it, we were just giving the URI the way we generate them `<http://..../co:123>`

**Comment by lmatteis** [comment]
But again, both of these work so perhaps your python lib isn't working?

```
$ curl http://www.cropontology.org/rdf/CO_020%3A90
$ curl http://www.cropontology.org/rdf/CO_020:90
```

**Comment by pypingou** [comment]
That they work it's normal, the http protocol substitute the html character and it works fine, but the URI created in the triples defers if they are  http://www.cropontology.org/rdf/CO_020%3A90 or  http://www.cropontology.org/rdf/CO_020:90

Maybe we should ask a someone with a better understanding of rdf (ansell?) what he thinks of this and maybe he can explain better than me or tell me I'm wrong (in which case I'll open a bug against rdflib :)).

**Comment by pypingou** [comment]
@ansell could you maybe help us figuring this out?

**Comment by ansell** [comment]
Sure. Is anyone from this group at ISWC this week by the way?

I don't have a development computer until I get back to he office next week if it ends up requiring that.

## 

Peter

**Comment by pypingou** [comment]
@ansell hi, thanks for helping, the debate we are having is regarding this page (for example) http://www.cropontology.org/rdf/CO_020:90 where as you can see the subject of the triples have the `:` encoded in html (thus appearing as `&3A`).

I am arguing that we should not do this, as we return a text output where the URI should appear as they are, with `:`. I know that otherwise, I cannot map  http://www.cropontology.org/rdf/CO_020%3A90 to http://www.cropontology.org/rdf/CO_020:90 

What do you think?

**Comment by lmatteis** [comment]
@pypingou so you have the IDs stored on your side with the `:` instead of the `%3A`? Perhaps you can run a bulk-update and convert them all to `%3A`? Not sure... perhaps @ansell knows more yes.

**Comment by pypingou** [comment]
@lmatteis that is an option, but I thing about this is we used not to have this and I know two applications where crop-ontologies URI have been integrated and on which I do not have any control.

Since it's still something that might not be very spread at the moment, I can contact the people and have them change the URI but let's make sure we're doing it correctly first :)

**Comment by lmatteis** [comment]
You're right. But I wonder, if we decide that `:` is the correct way of representing, how do we encode the identifiers? Say for example someone uploads something with an identifier such as "stem/height". The slash would be represented within the URI such as `http://www.cropontology.org/stem/height` creating effectively 2 URI components. Perhaps this is fine though...

**Comment by ansell** [comment]
That is the strategy that we use in Bio2RDF. Ie, the namespace, in this case the CO_NNN ontology identifier is followed by a colon and the. The identifier.

It may require splitting using a regex on the start of the input usinf the CO_NNN: pattern to get the two parts and then concatenate them after urlencoding just the identifier part, as the regex should be constructed to only match safe URL characters.

## 

Peter

**Comment by ansell** [comment]
It would be simpler if the original URI did not encode the colon if you can get in contact with them.

## 

Peter

**Comment by lmatteis** [comment]
Pierre, now CO shows the `:` in the URI. You're right, it's a valid identifier so you can use it http://www.cropontology.org/rdf/CO_322:0000103

**Comment by pypingou** [comment]
Awesome, this is going to make my life so much easier, thanks a lot! :)
