### ISSUE TITLE
Offer a simple method for downloading OBO

### ISSUE THREAD

**Issue by ansell** [bioversity/Crop-Ontology#32]
The website seems to be entirely focused on the RDF/SKOS downloading now, although OBO versions are available in the background. Is it possible to have an easy way to download the OBO versions, preferably using the API. In particular, the OBO version is downloaded using a URL that is impossible to guess, so you need to go through the sequence of physical browser clicks to get to it right now instead of being able to download it using a single URL.

For example, to download CO_715 I have the following three options:

Trait Template v4 : http://www.cropontology.org/report?ontology_id=CO_715 

RDF N-Triples SKOS : http://www.cropontology.org/ontology/CO_715/Crop%20Research/nt

OBO : http://www.cropontology.org/serve/AMIfv97g6GnRxEQ-xg8zg6AGoofvBkp3BerLYlzrWBCF1TW2hf1gr97w-v4G4h822bh2hxkY-8yvnwuwkXxz1nC4g7L3uRD8_sWNZwrO-HW8trWUKeNSmOoO5methsjhRe6qBKSZCICRrNtijIgdUdZ24qM2ayWb7PNDUaR-jsSwN_8qbZMIsfw

**Comment by lmatteis** [comment]
We're trying to make these three formats more interoperable as currently they are essentially kept as  3 different files. Actually the trait template and the RDF/SKOS are dynamically generated from the database, but for OBO we're still building the correct structure that would allow us to convert it into RDF and the other way around. 

But to answer your question, there's a little hack behind the door to get that long OBO string: http://www.cropontology.org/get-ontology-roots/CO_334 

`oboBlobKey` is what you want to put after http://www.cropontology.org/serve/

I know this is a hack for now, but we're soon to release a version 2 of Crop Ontology that would allow people to interoperate with OBO, RDF/SKOS and Excel, which requires a little bit of thinkering. 

Also, may I ask what you're using OBO for?

**Comment by ansell** [comment]
I am using OBO to convert to OWL, as I have an OWL based system (hence incompatible with SKOS based RDF).

I did figure out the get-ontology-roots hack and implemented it in my wrapper/client class: 

```
https://github.com/ansell/cropontology-java-client/blob/master/src/main/java/com/github/ansell/cropontology/CropOntologyClient.java
```
