### ISSUE TITLE
CO 322 contains invalid XREF attributes

### ISSUE THREAD

**Issue by ansell** [bioversity/Crop-Ontology#34]
The latest OBO to OWL converter reports that there are issues with CO 322 in relation to xref attributes:

Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 20  accepting bad xref with spaces:<Gramene Plant Trait Ontology:TO:0000463>  LINE:
xref: Gramene Plant Trait Ontology:TO:0000463
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 36  accepting bad xref with spaces:<Gramene Plant Trait Ontology:TO:0000495>  LINE:
xref: Gramene Plant Trait Ontology:TO:0000495
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 45  accepting bad xref with spaces:<Gramene Plant Trait Ontology:TO:0000359>  LINE:
xref: Gramene Plant Trait Ontology:TO:0000359
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 54  accepting bad xref with spaces:<Gramene Plant Trait Ontology:TO:0000396>  LINE:
xref: Gramene Plant Trait Ontology:TO:0000396
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 73  accepting bad xref with spaces:<Gramene Plant Trait Ontology:TO:0000207>  LINE:
xref: Gramene Plant Trait Ontology:TO:0000207
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 89  accepting bad xref with spaces:<Gramene Plant Trait Ontology:TO:0000365>  LINE:
xref: Gramene Plant Trait Ontology:TO:0000365
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 97  accepting bad xref with spaces:<Gramene Plant Trait Ontology:TO:0002759>  LINE:
xref: Gramene Plant Trait Ontology:TO:0002759
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 150  accepting bad xref with spaces:<Gramene Plant Trait Ontology:TO:0000683>  LINE:
xref: Gramene Plant Trait Ontology:TO:0000683
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 250  accepting bad xref with spaces:<Gramene Plant Trait Ontology:TO:0000658>  LINE:
xref: Gramene Plant Trait Ontology:TO:0000658
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 257  accepting bad xref with spaces:Gramene Plant Trait Ontology:TO:0000469  LINE:
def: "Number of days required from seeding to seed/grain ripening." [Gramene Plant Trait Ontology:TO:0000469]
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 267  accepting bad xref with spaces:<Gramene Plant Trait Ontology:TO:0000057>  LINE:
xref: Gramene Plant Trait Ontology:TO:0000057
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 325  accepting bad xref with spaces:<Gramene Plant Trait Ontology:TO:0000345>  LINE:
xref: Gramene Plant Trait Ontology:TO:0000345
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 930  accepting bad xref with spaces:Gramene Plant Trait Ontology:TO:0002667  LINE:
def: "Measures the abscisic acid content in a plant or plant part." [Gramene Plant Trait Ontology:TO:0002667]
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 938  accepting bad xref with spaces:Gramene Plant Trait Ontology:TO:0000333  LINE:
def: "Amount of sugar present in the plant or the plant part." [Gramene Plant Trait Ontology:TO:0000333]
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 945  accepting bad xref with spaces:Gramene Plant Trait Ontology:TO:0000300  LINE:
def: "Amount of glucose present in the plant or plant part." [Gramene Plant Trait Ontology:TO:0000300]
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 959  accepting bad xref with spaces:Gramene Plant Trait Ontology:TO:0000507  LINE:
def: "The ability of the plant to adjust the osmotic potential under stress conditions." [Gramene Plant Trait Ontology:TO:0000507]
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 973  accepting bad xref with spaces:Gramene Plant Trait Ontology:TO:0006002  LINE:
def: "Amino acid proline content in a plant or plant part." [Gramene Plant Trait Ontology:TO:0006002]
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 980  accepting bad xref with spaces:Gramene Plant Trait Ontology:TO:0000328  LINE:
def: "The amount of sucrose present in the plant or the plant part." [Gramene Plant Trait Ontology:TO:0000328]
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 1145  accepting bad xref with spaces:ISBN: 92-9043-189-1  LINE:
def: "Number of days from sowing to when 50% of the plants have a dry ear leaf." [CO:rs, ISBN: 92-9043-189-1]
Feb 03, 2014 2:54:56 PM org.obolibrary.oboformat.parser.OBOFormatParser warn
WARNING: LINE: 1167  accepting bad xref with spaces:ISBN: 92-9043-189-1  LINE:
def: "Kernel or grain color whether white, yellow, purple, variegated, brown, orange, mottled, white cap, red etc." [CO:rs, ISBN: 92-9043-189-1]

**Comment by lmatteis** [comment]
Thanks for this Peter. We will report this error to our ontology curators.
