### ISSUE TITLE
issue with multilingual ontologies

### ISSUE THREAD

**Issue by marieALaporte** [bioversity/Crop-Ontology#42]
Fix the download feature when the ontology is multilingual. 
The language selection does not seem to work

**Comment by gubi** [comment]
**Found the (big) bug: bad indexing.**

In the Datastore, a lot of terms are indexed with an "undefined" language prefix.
The language key is used to retrieve _blob_store_id_, so with an "undefined" language nothing works...
As default, "undefined" should be "english" or nothing (depending on the key).

For eg.: see the "oboBlobKey" result when the System collect `CO_020` data: http://www.cropontology.org/get-ontology-roots/CO_020

**Note**: this issue could be related to: #47 - #48 - #57 
Working on a fix that resolve all together...


Following data as displayed in the Datastore:
![image](https://user-images.githubusercontent.com/746559/45555673-b8549e00-b839-11e8-94bb-ed908c5de4a9.png)

**Comment by gubi** [comment]
As [here](https://github.com/bioversity/Crop-Ontology/blob/82863a9862d63664f68f054b2487cf94a4ddde22/main.js#L1903-L1910) file upload is pointed directly to Datastore `_/ah/upload/`, so filter data during inserting is not necessary.

Fixed as ba06f3adbd350c846052b5aae797844fb6d84bee
Please, reopen this issue if the problem will persist after the next release
