### ISSUE TITLE
Display of variables for a unit is not correct

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#45]
When one click on a unit like 'cm' under a trait and method, all variables using 'cm' as unit are displayed in the lower box. Should be modified to only display the variable corresponding to the trait.
![banana_onotlogy curation issue 3](https://user-images.githubusercontent.com/1417541/33654857-b56dab06-da71-11e7-8a28-81380fa269ae.png)

**Comment by gubi** [comment]
Seems a normal behaviour: as the code says, if you click on `cm` button you are asking _all variables of the current (clicked) term_.
So, if you want to show all trait variables just click on the trait name.

**Comment by marieALaporte** [comment]
fixed on new website
