### ISSUE TITLE
Tree not working when several traits share the same method

### ISSUE THREAD

**Issue by marieALaporte** [bioversity/Crop-Ontology#47]
e.g. Woody ontolgy

**Comment by gubi** [comment]
http://www.cropontology.org/ontology/CO_357/Woody%20Plant%20Ontology
This page?

**Comment by marieALaporte** [comment]
Yes, this is the only ontology we currently have that has multiple traits sharing the same method.

**Comment by gubi** [comment]
I'm trying to understand the error.
Can you please indicate the bug more precisely?

**Comment by gubi** [comment]
As [here](https://github.com/bioversity/Crop-Ontology/blob/82863a9862d63664f68f054b2487cf94a4ddde22/main.js#L1903-L1910) file upload is pointed directly to Datastore `_/ah/upload/`, so filter data during inserting is not necessary.

Fixed as ba06f3adbd350c846052b5aae797844fb6d84bee
Please, reopen this issue if the problem will persist after the next release
