### ISSUE TITLE
download of the mcpd ontology does not work

### ISSUE THREAD

**Issue by marieALaporte** [bioversity/Crop-Ontology#48]
The download of the mcpd ontology does not work. 
The file is now stored on the google could storage and not on the blobstore anymore

**Comment by gubi** [comment]
As [here](https://github.com/bioversity/Crop-Ontology/blob/82863a9862d63664f68f054b2487cf94a4ddde22/main.js#L1903-L1910) file upload is pointed directly to Datastore `_/ah/upload/`, so filter data during inserting is not necessary.

Fixed as ba06f3adbd350c846052b5aae797844fb6d84bee
Please, reopen this issue if the problem will persist after the next release
