### ISSUE TITLE
document all the API calls on the API call list

### ISSUE THREAD

**Issue by marieALaporte** [bioversity/Crop-Ontology#49]

**Comment by gubi** [comment]
In the file [main.js](../blob/appengine_plus_dev/main.js#L160-L4189) the object `apejs` contains all routes rules.

Here a comprehensive list of all coded routes (alphabetical ordered). I leave the regex for next developments:
* `/about`
* `/activate_user`
* `/add-attribute`
* `/add-comment` 
* `/add-ontology` 
* `/add-parent`
* `/admin`
* `/agtrials`
* `/api`
* `/attribute-redirect`
* `/attribute-upload-url`
* `/attribute-upload`
* `/backup`
* `/create-term`
* `/csv-download`
* `/curruser-ontologies`
* `/default-list`
* `/delete_user`
* `/delete-ontology`
* `/dump`
* `/edit_profile`
* `/edit-ontology` 
* `/edit-profile`
* `/excel-template-upload`
* `/excel-upload-url`
* `/feedback`
* `/forgot-password`
* `/get-attributes/(.*)`
* `/get-attributes/([^/]*)/jsonrdf`
* `/get-categories`
* `/get-children/(.*)`
* `/get-comments-onto` 
* `/get-comments` 
* `/get-ontologies`
* `/get-ontology-id`
* `/get-ontology-roots/([^/]*)`
* `/get-ontology/([^/]*)`
* `/get-term-parents/(.*)`
* `/get-term`
* `/get-terms-by-property`
* `/help`
* `/httpget`
* `/ibfieldbook`
* `/latest`
* `/login` 
* `/logout`
* `/memcache-clear`
* `/next-id`
* `/obo-to-json`
* `/obo-upload-url`
* `/obo-upload` 
* `/obo/([^/]*)`
* `/ontologies`
* `/ontology(?:/([^/]*)(?:/([^/]*)(?:/([^/]*))?)?)?`
* `/primary`
* `/rdf/([^/]*)`
* `/rdf/([^/]*)/(.*)`
* `/rebuild-search-index`
* `/register`
* `/remove-attribute`
* `/report`
* `/reset-password`
* `/search`
* `/serve` 
* `/serve/([^/]*)` 
* `/terms/([^/]*)/(.*)` 
* `/user-ontologies`
* `/users_admin`
* `/users`
* `/users/([a-zA-Z0-9_]+)`
* `/video-tutorials`

**Comment by gubi** [comment]
This page seems to be already done here: http://www.cropontology.org/api
Anyway, I would create a dedicated page (or enrich the existing api page) with the above list structured in this way:

> **API URL** (link)
> _Description_
> `Additional/technical informations`

> **API URL** (link)
> _Description_
> `Additional/technical informations`

> ...

Please, confirm if you agree

**Comment by gubi** [comment]
Added a dedicated page in the [wiki](https://github.com/bioversity/Crop-Ontology/wiki/All-API)
