### ISSUE TITLE
Download TD: categorical scales are weird

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#53]
whenever you download the TD from CO site a weird thing is happening with the categories, only 10 are presented in a randomized order, if more than ten categories those are being trimmed off the file. File attached is complete with all categories and in order.

**Comment by gubi** [comment]
Please can you better explain steps to reproduce the error?

**Comment by marieALaporte** [comment]
fixed in commit https://github.com/bioversity/Crop-Ontology/commit/d44388ed7d902a166270e393257f2550b8a3d6ec
