### ISSUE TITLE
list the deprecated api that the website is using

### ISSUE THREAD

**Issue by marieALaporte** [bioversity/Crop-Ontology#54]
list of the deprecated api can be found [here](https://cloud.google.com/appengine/docs/standard/java/javadoc/deprecated-list)

those classes will need to be rewritten to work with the new version of the google appengine

**Comment by gubi** [comment]
Following your link, this table represents all deprecated classes and objects used or not in the project scripts:


| Used by Crop-Ontology |    Family   | Deprecated item                         |
| :-------------------: | :---------: | :-------------------------------------- |
|           -           |   Package   | `com.google.appengine.api.channel`      |
|         **×**         |   Package   | `com.google.appengine.api.files`        |
|           -           |   Package   | `com.google.appengine.api.prospectivesearch` |
|           -           |   Package   | `com.google.appengine.api.xmpp`         |
|           -           |  Interface  | `com.google.appengine.api.backends.BackendService` |
|           -           |  Interface  | `com.google.appengine.api.channel.ChannelService` |
|         **×**         |  Interface  | `com.google.appengine.api.datastore.DatastoreConfig` |
|         **×**         |  Interface  | `com.google.appengine.api.files.FileReadChannel` |
|         **×**         |  Interface  | `com.google.appengine.api.files.FileService` |
|         **×**         |  Interface  | `com.google.appengine.api.files.FileWriteChannel` |
|           -           |  Interface  | `com.google.appengine.api.channel.IChannelServiceFactory` |
|         **×**         |  Interface  | `com.google.appengine.api.files.IFileServiceFactory` |
|           -           |  Interface  | `com.google.appengine.api.xmpp.IXMPPServiceFactory` |
|           -           |  Interface  | `com.google.appengine.api.prospectivesearch.ProspectiveSearchService` |
|         **×**         |  Interface  | `com.google.appengine.api.files.RecordReadChannel` |
|         **×**         |  Interface  | `com.google.appengine.api.files.RecordWriteChannel` |
|           -           |  Interface  | `com.google.appengine.api.xmpp.XMPPService` |
|         **×**         |    Class   | `com.google.appengine.api.files.AppEngineFile` |
|         **×**         |    Class   | `com.google.appengine.api.files.BufferedFileReadChannelImpl` |
|           -           |    Class   | `com.google.appengine.api.channel.ChannelMessage` |
|           -           |    Class   | `com.google.appengine.api.channel.ChannelPresence` |
|           -           |    Class   | `com.google.appengine.api.channel.ChannelServiceFactory` |
|         **×**         |    Class   | `com.google.appengine.api.files.Crc32c`  |
|           -           |    Class   | `com.google.appengine.api.xmpp.Error`    |
|           -           |    Class   | `com.google.appengine.api.xmpp.ErrorBuilder` |
|         **×**         |    Class   | `com.google.appengine.api.files.FileServiceFactory` |
|         **×**         |    Class   | `com.google.appengine.api.files.FileStat` |
|         **×**         |    Class   | `com.google.appengine.api.files.GSFileOptions` |
|           -           |    Class   | `com.google.appengine.api.channel.IChannelServiceFactoryProvider` |
|         **×**         |    Class   | `com.google.appengine.api.files.IFileServiceFactoryProvider` |
|           -           |    Class   | `com.google.appengine.api.xmpp.IXMPPServiceFactoryProvider` |
|           -           |    Class   | `com.google.appengine.api.xmpp.JID`      |
|           -           |    Class   | `com.google.appengine.api.xmpp.Message`  |
|           -           |    Class   | `com.google.appengine.api.xmpp.MessageBuilder` |
|           -           |    Class   | `com.google.appengine.api.xmpp.Presence` |
|           -           |    Class   | `com.google.appengine.api.xmpp.PresenceBuilder` |
|           -           |    Class   | `com.google.appengine.api.prospectivesearch.ProspectiveSearchServiceFactory` |
|           -           |    Class   | `com.google.appengine.api.xmpp.SendResponse` |
|           -           |    Class   | `com.google.appengine.api.prospectivesearch.Subscription` |
|           -           |    Class   | `com.google.appengine.api.xmpp.Subscription` |
|           -           |    Class   | `com.google.appengine.api.xmpp.SubscriptionBuilder` |
|           -           |    Class   | `com.google.appengine.api.xmpp.XMPPServiceFactory` |
|           -           |    Enum    | `com.google.appengine.api.prospectivesearch.FieldType` |
|           -           |    Enum    | `com.google.appengine.api.xmpp.MessageType` |
|           -           |    Enum    | `com.google.appengine.api.xmpp.PresenceShow` |
|           -           |    Enum    | `com.google.appengine.api.xmpp.PresenceType` |
|           -           |    Enum    | `com.google.appengine.api.xmpp.SubscriptionType` |
|           -           | Exceptions | `com.google.appengine.api.channel.ChannelFailureException` |
|         **×**         | Exceptions | `com.google.appengine.api.files.FinalizationException` |
|         **×**         | Exceptions | `com.google.appengine.api.files.KeyOrderingException` |
|         **×**         | Exceptions | `com.google.appengine.api.files.LockException` |
|           -           | Exceptions | `com.google.appengine.api.prospectivesearch.QuerySyntaxException` |
|           -           | Exceptions | `com.google.appengine.api.xmpp.XMPPFailureException` |
|         **×**         |   Fields   | `com.google.appengine.api.datastore.DatastoreConfig.DEFAULT` |
|         **×**         |   Fields   | `com.google.appengine.api.datastore.FetchOptions.DEFAULT_CHUNK_SIZE` |
|           -           |   Fields   | `com.google.appengine.api.utils.SystemProperty.instanceReplicaId` |
|         **×**         |   Fields   | `com.google.appengine.api.datastore.Query.KIND_METADATA_KIND` |
|         **×**         |   Fields   | `com.google.appengine.api.datastore.Query.NAMESPACE_METADATA_KIND` |
|         **×**         |   Fields   | `com.google.appengine.api.datastore.Query.PROPERTY_METADATA_KIND` |
|           -           |   Fields   | `com.google.appengine.api.images.ImagesService.SERVING_CROP_SIZES` |
|           -           |   Fields   | `com.google.appengine.api.images.ImagesService.SERVING_SIZES` |
|         **×**         |   Method   | `com.google.appengine.api.datastore.Query.addFilter(String, Query.FilterOperator, Object)` |
|         **×**         |   Method   | `com.google.appengine.api.datastore.TransactionOptions.Builder.allowMultipleEntityGroups(boolean)` |
|         **×**         |   Method   | `com.google.appengine.api.datastore.TransactionOptions.allowsMultipleEntityGroups()` |
|         **×**         |   Method   | `com.google.appengine.api.datastore.TransactionOptions.clearMultipleEntityGroups()` |
|         **×**         |   Method   | `com.google.appengine.api.datastore.PreparedQuery.countEntities()` |
|           -           |   Method   | `com.google.appengine.api.users.UserService.createLoginURL(String, String, String, Set<String>)` |
|         **×**         |   Method   | `com.google.appengine.api.datastore.FetchOptions.cursor(Cursor)` |
|           -           |   Method   | `com.google.appengine.api.search.Index.deleteSchema()` |
|           -           |   Method   | `com.google.appengine.api.search.Index.deleteSchemaAsync()` |
|           -           |   Method   | `com.google.appengine.api.log.RequestLogs.getApiMcycles()` |
|           -           |   Method   | `com.google.appengine.api.quota.QuotaService.getApiTimeInMegaCycles()` |
|         **×**         |   Method   | `com.google.appengine.api.datastore.FetchOptions.getCursor()` |
|         **×**         |   Method   | `com.google.appengine.api.datastore.DatastoreServiceFactory.getDatastoreService(DatastoreConfig)` |
|         **×**         |   Method   | `com.google.appengine.api.datastore.DatastoreServiceFactory.getDefaultDatastoreConfig()` |
|         **×**         |   Method   | `com.google.appengine.api.datastore.Query.getFilterPredicates()` |
|         **×**         |   Method   | `com.google.appengine.api.datastore.DatastoreConfig.getImplicitTransactionManagementPolicy()` |
|         **×**         |   Method   | `com.google.appengine.api.memcache.ErrorHandlers.getLogAndContinue(Level)` |
|           -           |   Method   | `com.google.appengine.api.oauth.OAuthService.getOAuthConsumerKey()` |
|           -           |   Method   | `com.google.apphosting.api.ApiProxy.Environment.getRequestNamespace()` |
|           -           |   Method   | `com.google.appengine.api.search.ISearchServiceFactory.getSearchService(String)` |
|         **×**         |   Method   | `com.google.appengine.api.search.SearchServiceFactory.getSearchService(String)` |
|           -           |   Method   | `com.google.appengine.api.images.ImagesService.getServingUrl(BlobKey)` |
|           -           |   Method   | `com.google.appengine.api.images.ImagesService.getServingUrl(BlobKey, boolean)` |
|           -           |   Method   | `com.google.appengine.api.images.ImagesService.getServingUrl(BlobKey, int, boolean)` |
|           -           |   Method   | `com.google.appengine.api.images.ImagesService.getServingUrl(BlobKey, int, boolean, boolean)` |
|           -           |   Method   | `com.google.appengine.api.search.ScoredDocument.getSortScores()` |
|           -           |   Method   | `com.google.appengine.api.blobstore.BlobstoreService.getUploadedBlobs(HttpServletRequest)` |
|         **×**         |   Method   | `com.google.appengine.api.taskqueue.QueueConstants.maxTaskSizeBytes()` |
|         **×**         |   Method   | `com.google.appengine.api.datastore.TransactionOptions.multipleEntityGroups(boolean)` |
|         **×**         |   Method   | `com.google.appengine.api.datastore.Cursor.reverse()` |
|         **×**         |   Method   | `com.google.appengine.api.memcache.MemcacheService.setNamespace(String)` |
|         **×**         |   Method   | `com.google.appengine.api.datastore.FetchOptions.Builder.withCursor(Cursor)` |
|         **×**         | Constructor | `com.google.appengine.api.datastore.DatastoreServiceFactory()` |
|         **×**         | Constructor | `com.google.apphosting.api.ApiProxy.LogRecord(ApiProxy.LogRecord.Level, long, String, Throwable)` |
|         **×**         | Constructor | `com.google.appengine.api.taskqueue.TaskHandle(String, String, long)` |

**Comment by gubi** [comment]
By the way, this is a list of all used classes:

| Script  | Used class | Deprecation warning |
| :-----  | :--------- | :--------: |
| [auth.js](https://github.com/bioversity/Crop-Ontology/blob/appengine_plus_dev/auth.js#L1) | `javax.servlet.http` | - |
| [blobstore.js](https://github.com/bioversity/Crop-Ontology/blob/appengine_plus_dev/blobstore.js#L1) | `com.google.appengine.api.blobstore` | **×** |
| [blobstore.js](https://github.com/bioversity/Crop-Ontology/blob/appengine_plus_dev/blobstore.js#L2) | `com.google.appengine.api.files` | **×** |
| [email.js](https://github.com/bioversity/Crop-Ontology/blob/appengine_plus_dev/email.js#L1) | `javax.mail` | - |
| [email.js](https://github.com/bioversity/Crop-Ontology/blob/appengine_plus_dev/email.js#L2) | `javax.mail.internet` | - |
| [excel.js](https://github.com/bioversity/Crop-Ontology/blob/appengine_plus_dev/excel.js#L1) | `org.apache.poi.ss.usermodel` | - |
| [excel.js](https://github.com/bioversity/Crop-Ontology/blob/appengine_plus_dev/excel.js#L2) | `org.apache.poi.hssf.usermodel` | - |
| [fileupload.js](https://github.com/bioversity/Crop-Ontology/blob/appengine_plus_dev/fileupload.js#L1) | `org.apache.commons.fileupload` | - |
| [fileupload.js](https://github.com/bioversity/Crop-Ontology/blob/appengine_plus_dev/fileupload.js#L2) | `org.apache.commons.fileupload.servlet` | - |
| [fileupload.js](https://github.com/bioversity/Crop-Ontology/blob/appengine_plus_dev/fileupload.js#L3) | `org.apache.commons.io` | - |
| [fileupload.js](https://github.com/bioversity/Crop-Ontology/blob/appengine_plus_dev/fileupload.js#L4) | `com.google.appengine.api.datastore` | **×** |
| [taskqueue.js](https://github.com/bioversity/Crop-Ontology/blob/appengine_plus_dev/taskqueue.js#L1) | `com.google.appengine.api.taskqueue` | **×** |
| WEB-INF/modules/[googlestore.js](https://github.com/bioversity/Crop-Ontology/blob/appengine_plus_dev/WEB-INF/modules/googlestore.js#L5) | `com.google.appengine.api.datastore` | **×** |
| WEB-INF/modules/[memcache.js](https://github.com/bioversity/Crop-Ontology/blob/appengine_plus_dev/WEB-INF/modules/memcache.js#L1) | `com.google.appengine.api.memcache` | **×** |
| WEB-INF/modules/[select.js](https://github.com/bioversity/Crop-Ontology/blob/appengine_plus_dev/WEB-INF/modules/select.js#L1) | `com.google.appengine.api.datastore` | **×** |

**Comment by gubi** [comment]
### Stats
**46** of total 97 deprecated API are used by the project
**9** scripts are using classes with incompatibility risk for next versions of Java

**Comment by gubi** [comment]
See also: [Migration from deprecated Managed VMs to Flexible Environment](https://github.com/dart-lang/appengine/wiki/Migration-from-deprecated-Managed-VMs-to-Flexible-Environment)

**Comment by gubi** [comment]
I performed global search inside the code with deprecated functions as key.
This is the result.

#### `com.google.appengine.api.blobstore`
Status: Fixed as [#4e7cdfe](https://github.com/bioversity/Crop-Ontology/commit/4e7cdfeeaeb179a536c9374711b7d6387f0d9545) _(see also [this issue](https://github.com/bioversity/Crop-Ontology/issues/56))_

#### `com.google.appengine.api.files`
Status: Unresolved - Core platform change is needed

![immagine](https://user-images.githubusercontent.com/746559/44533926-dfb2c200-a6f6-11e8-8947-1e8a14e2a8ac.png)


#### `com.google.appengine.api.datastore`
Status: no deprecated functions used

#### `com.google.appengine.api.taskqueue`
Status: no deprecated functions used

#### `com.google.appengine.api.memcache`
Status: no deprecated functions used
