### ISSUE TITLE
Excel and PDF export of the ontologies

### ISSUE THREAD

**Issue by gubi** [bioversity/Crop-Ontology#59]
_Currently, only a csv export is possible.
The code allowing the excel export has been developed, works locally but does not work on the online server. Nothing has been done for pdf. The structure of the file will have to be discussed._

**Comment by kadreher** [comment]
Hi @marieALaporte . Hi from Texcoco. Will this request be implemented at some point? Many thanks.

**Comment by marieALaporte** [comment]
excel download is now possible
