### ISSUE TITLE
Automatic sync between OBO files

### ISSUE THREAD

**Issue by gubi** [bioversity/Crop-Ontology#63]
OBO files are pushed on github (e.g. https://github.com/Planteome/ibp-cassava-traits/blob/master/cassava_trait.obo).
The idea is to have an automatic sync between the content of the file on github and the Crop Ontology website database. What needs to be done:
- [ ] Have the CO website listening to the google repo and get only the information that changed (diffs)
- [ ] Develop methods to update an existing term or create an existing term or remove an existing term based on the diff.

**Comment by gubi** [comment]
Is there a specific repository to listen?
As [documented here](https://developer.github.com/v3/activity/events/types/#pushevent) I can create a web hook which listen changes but I have to set it _where_.

**Comment by marieALaporte** [comment]
https://github.com/Planteome/ibp-cassava-traits/blob/master/cassava_trait.obo
