### ISSUE TITLE
Final checks

### ISSUE THREAD

**Issue by gubi** [bioversity/Crop-Ontology#66]
Lastly - as also noted [here](https://github.com/bioversity/Crop-Ontology/issues/54#issuecomment-415016564) - check the following features on the production website:

- [x] Login
- [x] Searches
- [x] Send some email from server (e.g. creating a new account and the deleting it)
- [ ] Upload some files (and checking tasks job on the admin)

**Comment by marieALaporte** [comment]
Send some email from server (e.g. creating a new account and the deleting it) - I haven't tried it but got several email in the last week of people creating account. So I assume this works fine

**Comment by gubi** [comment]
:+1:

**Comment by gubi** [comment]
Is it possible to upload a file and then remove it?
Just to test if everything works as well
