### ISSUE TITLE
Access and Display of the upper banner for each crop ontology

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#68]
Each ontology has a banner with a photo and names of contributors. The update of this banner is not easy and direct. Could you propose a solution that would ease the update of this part of the page?

**Comment by gubi** [comment]
Each banner is a static HTML file, I guess: https://github.com/bioversity/Crop-Ontology/blob/appengine_plus_dev/main.js#L551-L571

![image](https://user-images.githubusercontent.com/746559/45906180-72787680-bdf3-11e8-983b-cced87fb4598.png)

Is there a specific reason why this is so?
An automated version can be available with next release.

**Comment by gubi** [comment]
I created a [JSON file with all indexed ontology data](https://github.com/bioversity/Crop-Ontology/blob/dev/public/ontologies_data.json), so you can simply add necessary data
