### ISSUE TITLE
Statistic of the site

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#69]
We have a link (which I always forget) to access some statistics on the site: number of crops, of triats, variables .. Would it be possible to have a direct visualization of this or at least store the link on the site?

**Comment by marieALaporte** [comment]
you mean this: http://www.cropontology.org/ontos_stats ?

**Comment by elizabetharnaud** [comment]
yes!

**Comment by gubi** [comment]
I can add a link in the menu, just between "API" and "help" ([here](https://github.com/bioversity/Crop-Ontology/blob/appengine_plus_dev/skins/index.html#L156-L159)), and make it available in the next release.
Regarding the link text: "Onto stats" is ok?

**Comment by gubi** [comment]
I think the link could stay better in the footer, just between "API" and "Feedback".

![image](https://user-images.githubusercontent.com/746559/45943339-2e999300-bfe6-11e8-90d7-ce2bd3acf0e9.png)

**Comment by marieALaporte** [comment]
I think it will be best if it can be listed on the API calls page

**Comment by gubi** [comment]
here: http://www.cropontology.org/api?

**Comment by marieALaporte** [comment]
yes

**Comment by gubi** [comment]
Please, close the issue if it's ok

**Comment by marieALaporte** [comment]
It looks ok to me. 
I let it open in case some day we have time to work on some visualizations as proposed by @elizabetharnaud
