### ISSUE TITLE
Crop Research Ontology - enable a download

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#70]
We should discuss how to download the Crop Research Ontology from CO or rout to AgrO on OLS? - being used by MIAPPE

**Comment by marieALaporte** [comment]
Crop Research Ontology has been [archived](https://github.com/bioversity/crop-research-ontology) as it was not maintained anymore. We recommend to use [AgrO](https://github.com/AgriculturalSemantics/agro) in place of Crop Research Ontology
