### ISSUE TITLE
Trait classe naming

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#71]
Apparently we have 2 ways of naming the trait classes:
'Agronomic' AND 'Agronmic traits'
Difference between Guidelines and Readme file + no consistentcy checking on the Excel file.
this has leaded to the duplication of classes when INRA merged their ontology with the CIMMYT one and perhaps is  also the problem for Sunflower. To be checked and corrected in the guidelines and in the Ontology TD template.

**Comment by elizabetharnaud** [comment]
We corrected by indicating  in the guidelines and Readme file call names without the word 'trait' from the class name.
However, the class name which becomes an adjective cannot then be made independent of the root indicating it is about a 'Trait'. is this ontologically acceptable as class name? can this pose a problem if traits or classes are reused in another ontology which is not about traits?

**Comment by marieALaporte** [comment]
this is harmonized now
