### ISSUE TITLE
URL of Crop Ontogy in Https?

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#72]
I think I remember that Marie mentiond a problem with the fact that CO site is not in the https:// protocol and it poses problems for linking with sites like Github for example.
 Did you discuss solving this ?

**Comment by gubi** [comment]
[http**s**://www.cropontology.org/](https://www.cropontology.org/)

Done with a self-signed certificate ([Let’s Encrypt](https://letsencrypt.org/)).

**Comment by gubi** [comment]
Also activated DNSSEC ([documentation](https://www.icann.org/resources/pages/dnssec-qaa-2014-01-29-en) - [animated video](https://www.youtube.com/watch?v=lTABuMxO2AM))
