### ISSUE TITLE
Dynamic  update of the homepage

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#75]
The new web page must  be updated dynamically when a new ontology is uploaded on our web site . e.g. Faba bean ontology was uploaded 4 days ago and appears on the cropontology.org web site but not on the new home page.

**Comment by gubi** [comment]
Fixed.
Due CORS (Cross-Origin Resource Sharing) policies I downloaded locally the list of ontologies, but was only temporary and because I worked on it
