### ISSUE TITLE
Display of the Variable: problem

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#81]
In the list , the variable name is attached to the trait while, in the old site,  it was in the separate windows under the list to show the variables names. This window can appear elsewhere, on the side , but rthe variable name should not appear where it is today.
![capture d ecran 2019-01-16 12 01 55](https://user-images.githubusercontent.com/1417541/51278153-b1c46780-198e-11e9-9e13-115bf81424d7.png)
![capture d ecran 2019-01-16 12 06 37](https://user-images.githubusercontent.com/1417541/51278163-b721b200-198e-11e9-957e-0b541517e80d.png)

**Comment by gubi** [comment]
In the new interface I placed the variable list on the top-right box, inside the "Term information" box.
Did you see it?

![image](https://user-images.githubusercontent.com/746559/51803596-48c6d480-2257-11e9-82ea-0a9b033bb942.png)
