### ISSUE TITLE
Error message for Login

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#88]
I changed my password  ( it brings me to the old site for changing the passwrod) and came back to the new site for login .
I got the error message in red.
![capture d ecran 2019-01-20 10 49 03](https://user-images.githubusercontent.com/1417541/51437645-4259bb00-1ca1-11e9-9cf5-7dcac6d8a633.png)

**Comment by gubi** [comment]
Does it still exists?
