### ISSUE TITLE
site blocked after I post a feedback

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#89]
I went to the feedback window, logged in using DisqUs. Posted a comment and then the site was blocked. no way to click anywhere anymore like go backto the home page , open another window, nothing...
![capture d ecran 2019-01-20 10 55 48](https://user-images.githubusercontent.com/1417541/51437702-f5c2af80-1ca1-11e9-8c08-dcda0895edd0.png)

**Comment by gubi** [comment]
Seems a browser's crash.
Please, can you share more informations, such as the browser type?
