### ISSUE TITLE
Incomplete display of data

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#92]
By Tom: Wheat: Scales are not always listed while they do exist in the download. The example below is “Bread crumb structure”: Trait and method are shown, but scale is missing. This occurs also for other Wheat traits *AND* other crops such as Sunflower (Quality and Biochem. traits) and Yam (Quality traits).
![image 1](https://user-images.githubusercontent.com/1417541/92925404-bb8bc000-f43a-11ea-8d05-65cab46d50c0.png)

**Comment by marieALaporte** [comment]
fixed
