### ISSUE TITLE
Incomplete Display of Data 2

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#93]
For Cotton the problem is different: the trait, method and scales boxes show up, but the descriptive text is missing for all of them! Only CO id and creation data are displayed in the term information window (right hand side)
![image2](https://user-images.githubusercontent.com/1417541/92925500-e0803300-f43a-11ea-998f-5e160df751be.png)

**Comment by marieALaporte** [comment]
fixed now
