### ISSUE TITLE
Incorrect display of data

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#94]
In the Woody plants ontology there is a different problem that seems to indicate that there is a logical (programming) error. Look at the amount of scales showing up under trait “Drought damage” and method “Visual scoring”!!
In this particular ontology the method “Visual scoring” is used for many different traits, but in combination with trait “Drought damage” it should only list the “Drought damages scoring scale” (which is somewhere further down the list of scales). Instead it fetches *ALL* scales linked to the method “Visual scroring” irrespective of the trait!
![image 3](https://user-images.githubusercontent.com/1417541/92925599-04dc0f80-f43b-11ea-8e0b-6f772a2c31d1.png)

**Comment by marieALaporte** [comment]
solved in new website
