### ISSUE TITLE
Data Quality Control issue

### ISSUE THREAD

**Issue by elizabetharnaud** [bioversity/Crop-Ontology#95]
In the current setup both the CO-team members  *AND* individual curators can upload new versions of ontologies. We do extra checks when we upload, but we have no control whatsoever what curators do! The current application might perform some checks, but these checks don’t seem very robust! See below where “Physiological” and “Quality” occur twice as trait categories. This is probably due to trailing or leading blanks (space character). We also have inconsistencies in trait naming (all lower caps, some init. caps etc.). It’s essential to consider (also for the new app development!) how to improve and implement a more consistent data quality control system.
![image4](https://user-images.githubusercontent.com/1417541/92925736-3b198f00-f43b-11ea-908e-a80dc221e134.png)

**Comment by marieALaporte** [comment]
done with the td checking tool
