### ISSUE TITLE
Scale min-max values to be linked to variable ID not scale ID

### ISSUE THREAD

**Issue by TomHazekam** [bioversity/Crop-Ontology#96]
Min and max values are linked to scale _ID, but should be linked to Variable_ID as they are the range for the variable.

**Comment by marieALaporte** [comment]
An easy fix with the current system would be to update the Template by moving this information to the variable section. During the upload the information will therefore be attached to the variable in the database. 
Not sure though if this will be correctly exported back when you download the td from the site. Something to test!

**Comment by elizabetharnaud** [comment]
We discussed the template update this way  indeed and this new version could be used for new crops but we will need to update the previous ones. We could re-upload each ontology but we need to fix some issues 1st. Carlos has proposed to look at this issue in the sequence of the site redevelopment.
