### ISSUE TITLE
Editing of attributes not working correctly

### ISSUE THREAD

**Issue by TomHazekam** [bioversity/Crop-Ontology#99]
When I tried to edit an ordinal scale attribute Category names are assigned incorrectly, categories are not deleted etc. Pls see screenshot below.
![image](https://user-images.githubusercontent.com/45200351/94153352-95234700-fe74-11ea-84eb-cef9fb74da98.png)

**Comment by marieALaporte** [comment]
closing as this process is done differently on new website
